### ISSUE TITLE
Build not honoring ENABLE_PYTHON=OFF

### ISSUE THREAD

**Issue by boogachamp** [sandialabs/gr-timing_utils#2]
When disabling Python/Swig gnuradio support the build fails.

Used cmake -DENABLE_PYTHON:BOOL=OFF flag to set

**Comment by boogachamp** [comment]
Fixed locally by wrapping the addition of subdirectories:

if (ENABLE_PYTHON)
    add_subdirectory(swig)
    add_subdirectory(python)
endif(ENABLE_PYTHON)

**Comment by jacobgilbert-snl** [comment]
Fixed in 2d1a814505bf8dfd4664f7539c12e26de7c0c59c
